feat(contracts): implement ShadowGroup multisig
quartz-technology/0xShadows-ethglobal-circuit-breaker-2024 pull request #1
Opened 2024-02-13 21:55 UTC by 0xpanoramix

## Description

Please provide a detailed description of what was done in this PR.

## Changes include

- [ ] Bugfix (non-breaking change that solves an issue).
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention).
- [ ] New feature (non-breaking change that adds functionality).
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality).
- [ ] Documentation update (change added to any kind of documentation).

## Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it.

## Checklist

- [ ] I have assigned this PR to myself.
- [ ] I have added at least 1 reviewer.
- [ ] I have added the relevant labels.
- [ ] I have updated the official documentation.
- [ ] I have added sufficient documentation in code.

## Testing

- [ ] I have tested this code with the official test suite.
- [ ] I have tested this code manually.

### Manual tests

Please complete this section if you ran manual tests for this functionality, otherwise delete it.

## Documentation update

Please link the documentation update PR in this section if it's present, otherwise delete it.

## Additional comments

Please post additional comments in this section if you have them, otherwise delete it.

2024-02-13 23:02 UTC, 0xtekgrinder requested changes
Overall, use custom errors and a few changes to do. I don't know if it is possible with semaphores but it would be better to achieve to works without transactions array and instead use the signatures and all the data of the tx in executeTransaction

2024-02-14 18:39 UTC, 0xpanoramix commented on contracts/contracts/ShadowGroup.sol
> +        uint value;
Fixed in 531d38c030abe585a8fffed5055229a54cfeabe6

2024-02-14 19:53 UTC, 0xpanoramix commented on contracts/contracts/ShadowGroup.sol
> +        semaphore.createGroup(groupID, 20, address(this));
It allows to create a group with 2^20 members and is the default value used in the Semaphore TS client.
More than enough, and can not be less than 16.

2024-02-14 20:20 UTC, 0xpanoramix commented on contracts/contracts/ShadowGroup.sol
> +        require(_txIndex < transactions.length, "tx does not exist");
Fixed in 1748944f78c0ecb3d32de587ddd8fbfc6839db50.

2024-02-14 20:20 UTC, 0xpanoramix commented on contracts/contracts/ShadowGroup.sol
> +        require(!transactions[_txIndex].executed, "tx already executed");
Fixed in 1748944f78c0ecb3d32de587ddd8fbfc6839db50.

2024-02-14 20:22 UTC, 0xpanoramix commented on contracts/contracts/ShadowGroup.sol
> +    }
Updated in e15f8dda03c973b91104f1a4e146e5d0941f74d8

2024-02-14 20:39 UTC, 0xpanoramix commented on contracts/contracts/ShadowGroup.sol
> +    }
Nice comment ! Updated in 95c76dc4fbf3bc28139d48133ee5f763b5dea049.

2024-02-15 07:59 UTC, 0xtekgrinder requested changes

2024-02-15 07:59 UTC, 0xtekgrinder commented on contracts/contracts/ShadowGroup.sol
> +        require(success, "tx failed");
custom error

2024-02-15 18:50 UTC, 0xpanoramix commented on contracts/contracts/ShadowGroup.sol
> +        require(success, "tx failed");
Fixed in e839f2d2a1325c87a4758939063af8a1e7932ac8.

2024-02-15 18:51 UTC, merged